language: python
python:
 - "3.9"
install:
 - pip install -r requirements.txt
 - pip install pytest
 - pip install pytest-cov 
 - pip install coveralls

script:
 - python -m pytest --cov=. tests/
#- pytest --cov=micropeutist_app tests/
# - coverage run -m pytest tests/test_by_pytest.py
after_success: coveralls

