language: python
python:
 - 3.9
install:
 - pip install -r requirements.txt
 - pip install coveralls
script:
 - pytest tests/temp_pytest.py
 - coverage run -m pytest tests/temp_pytest.py
 after_success:
 - coveralls