language: python
python:
 - "3.9"
install:
 - pip install -r requirements.txt
 - pip install pytest
 - pip install pytest-cov 
 - pip install coveralls
services:
 - mysql

script:
 - python -m pytest --cov=. tests/

after_success: coveralls

