language: python

services:
 - mysql

python:
 - "3.9"

env:
 - DB_USER=root

before_install:
 - mysql -e 'CREATE DATABASE micropeutist;'

install:
 - pip install -r requirements.txt
 - pip install pytest
 - pip install pytest-cov 
 - pip install coveralls

script:
 - python -m pylint micropeutist
 - flask db upgrade
 - python -m pytest --cov=micropeutist tests/

after_success: coveralls
